import BgCanvas from '@components/layout/BgCanvas';
import HeaderCanvas from '@components/layout/HeaderCanvas';
import Navbar from '@components/layout/Nav';
import type { Metadata } from 'next';
import React from 'react';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderCanvas />
        <BgCanvas />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
