import type { Metadata } from "next";
import React from "react";

import Navbar from "@/components/Nav";

import BgCanvas from "./components/BgCanvas";
import HeaderCanvas from "./components/HeaderCanvas";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderCanvas />
        <BgCanvas />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
